-- 为RCS_UserTasks表添加新增字段
-- 执行前请备份数据库

-- 检查字段是否存在，如果不存在则添加
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RCS_UserTasks' AND COLUMN_NAME = 'MaterialCode')
BEGIN
    ALTER TABLE RCS_UserTasks ADD MaterialCode NVARCHAR(100) NULL;
    PRINT '已添加字段 MaterialCode';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RCS_UserTasks' AND COLUMN_NAME = 'MaterialQuantity')
BEGIN
    ALTER TABLE RCS_UserTasks ADD MaterialQuantity INT NOT NULL DEFAULT 0;
    PRINT '已添加字段 MaterialQuantity';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RCS_UserTasks' AND COLUMN_NAME = 'PalletNumber')
BEGIN
    ALTER TABLE RCS_UserTasks ADD PalletNumber NVARCHAR(100) NULL;
    PRINT '已添加字段 PalletNumber';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RCS_UserTasks' AND COLUMN_NAME = 'SourceType')
BEGIN
    ALTER TABLE RCS_UserTasks ADD SourceType NVARCHAR(50) NULL;
    PRINT '已添加字段 SourceType';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RCS_UserTasks' AND COLUMN_NAME = 'DestType')
BEGIN
    ALTER TABLE RCS_UserTasks ADD DestType NVARCHAR(50) NULL;
    PRINT '已添加字段 DestType';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RCS_UserTasks' AND COLUMN_NAME = 'ConfirmTime')
BEGIN
    ALTER TABLE RCS_UserTasks ADD ConfirmTime DATETIME NULL;
    PRINT '已添加字段 ConfirmTime';
END

PRINT 'RCS_UserTasks表字段更新完成！' 